import 'package:moon_event/model/event.dart';

List<Event> generatedEvents = [
  Event(
    title: "Fintech Conference 2024",
    description: "An exciting conference on the future of Fintech.",
    date: DateTime(2024, 12, 10),
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    location: "San Francisco, CA",
    imageUrl: "1",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1", // Organizer: Uch Mengly6
    participantsWillAttend: [
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Uch Mengly4
      "VCYZdLohGbU2vqtd5yRPZTTPXln1"  // Uch Mengly5
    ],
    participantsJoined: [
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2" // Uch Mengly3
    ],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc", // Category: Fintech
    participantCount: 3,
  ),
  Event(
    title: "AI & Machine Learning Summit",
    description: "Dive deep into AI technologies and trends.",
    date: DateTime(2024, 12, 15),
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    location: "New York, NY",
    imageUrl: "2",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Organizer: Uch Mengly4
    participantsWillAttend: [
      "dYDsm4Vogjc4LWLGMaSZCIufQux1", // Uch Mengly8
      "iP8HPYBpQnWIfS3m98jZLZ3MNmW2", // Uch Mengly
      "m18RsrYElTR0tTjyaiuevIIAUjf2"  // Uch Mengly2
    ],
    participantsJoined: [
      "iP8HPYBpQnWIfS3m98jZLZ3MNmW2" // Uch Mengly
    ],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e", // Category: Artificial Intelligence
    participantCount: 3,
  ),
  Event(
    title: "Cyber Security Forum",
    description: "Experts discuss the latest in cybersecurity.",
    date: DateTime(2024, 12, 12),
    startTime: "1:00 PM",
    endTime: "6:00 PM",
    location: "Los Angeles, CA",
    imageUrl: "3",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Organizer: Uch Mengly3
    participantsWillAttend: [
      "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2"  // Uch Mengly7
    ],
    participantsJoined: [
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2" // Uch Mengly7
    ],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886", // Category: Cyber Security
    participantCount: 2,
  ),
  Event(
    title: "Blockchain Trends 2024",
    description: "Exploring advancements in blockchain technology.",
    date: DateTime(2024, 12, 18),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Miami, FL",
    imageUrl: "4",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1", // Uch Mengly6
    participantsWillAttend: [
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc", // Fintech
    participantCount: 3,
  ),
  Event(
    title: "AI in Healthcare",
    description: "The impact of AI on medical advancements.",
    date: DateTime(2024, 12, 20),
    startTime: "9:30 AM",
    endTime: "2:30 PM",
    location: "Seattle, WA",
    imageUrl: "5",
    organizerId: "iP8HPYBpQnWIfS3m98jZLZ3MNmW2", // Uch Mengly
    participantsWillAttend: [
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2",
      "m18RsrYElTR0tTjyaiuevIIAUjf2"
    ],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e", // Artificial Intelligence
    participantCount: 3,
  ),
  Event(
    title: "Cyber Security in Fintech",
    description: "How cybersecurity protects financial systems.",
    date: DateTime(2024, 12, 22),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Dallas, TX",
    imageUrl: "6",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
    participantsWillAttend: [
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1"
    ],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886", // Cyber Security
    participantCount: 2,
  ),
  Event(
    title: "UI/UX Bootcamp",
    description: "Learn UI/UX design from the best.",
    date: DateTime(2024, 12, 25),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Chicago, IL",
    imageUrl: "7",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Uch Mengly4
    participantsWillAttend: [
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2"
    ],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620", // UI/UX Design
    participantCount: 3,
  ),
  Event(
    title: "Digital Marketing Workshop",
    description: "Grow your business with digital marketing.",
    date: DateTime(2024, 12, 28),
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    location: "Austin, TX",
    imageUrl: "8",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: true,
    categoryId: "e0359913-2024-447a-bfd2-edff6a9a0728", // Digital Marketing
    participantCount: 3,
  ),
  Event(
    title: "Data Science Hackathon",
    description: "Collaborate and innovate in the data science domain.",
    date: DateTime(2024, 12, 30),
    startTime: "8:00 AM",
    endTime: "8:00 PM",
    location: "Boston, MA",
    imageUrl: "9",
    organizerId: "m18RsrYElTR0tTjyaiuevIIAUjf2", // Uch Mengly2
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1"
    ],
    participantsJoined: ["CqPG0YgwBzaUgDQaTIE6DdToXHZ2"],
    isPublic: true,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f", // Data Science
    participantCount: 3,
  ),
  Event(
    title: "AI in Gaming",
    description: "How AI is transforming the gaming industry.",
    date: DateTime(2025, 1, 5),
    startTime: "1:00 PM",
    endTime: "6:00 PM",
    location: "Orlando, FL",
    imageUrl: "10",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Uch Mengly4
    participantsWillAttend: [
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "iP8HPYBpQnWIfS3m98jZLZ3MNmW2",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2"
    ],
    participantsJoined: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e", // Artificial Intelligence
    participantCount: 3,
  ),
  Event(
    title: "Web Development for Beginners",
    description: "A beginner's guide to web and app development.",
    date: DateTime(2025, 1, 10),
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    location: "Las Vegas, NV",
    imageUrl: "11",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "m18RsrYElTR0tTjyaiuevIIAUjf2"
    ],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb", // Web/App Development
    participantCount: 3,
  ),
  Event(
    title: "The Future of Fintech",
    description: "Exploring what’s next for financial technology.",
    date: DateTime(2025, 1, 15),
    startTime: "9:30 AM",
    endTime: "12:30 PM",
    location: "Houston, TX",
    imageUrl: "12",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
    participantsWillAttend: [
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1"
    ],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc", // Fintech
    participantCount: 3,
  ),
  Event(
    title: "Secure Software Development",
    description: "Develop secure applications with best practices.",
    date: DateTime(2025, 1, 20),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Denver, CO",
    imageUrl: "13",
    organizerId: "iP8HPYBpQnWIfS3m98jZLZ3MNmW2", // Uch Mengly
    participantsWillAttend: [
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "AqsauIfPHxajYR20eiqGHxyDWxl1"
    ],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886", // Cyber Security
    participantCount: 3,
  ),
  Event(
    title: "Mobile App Design Trends 2025",
    description: "Stay ahead with the latest in mobile app design.",
    date: DateTime(2025, 1, 25),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Phoenix, AZ",
    imageUrl: "14",
    organizerId: "m18RsrYElTR0tTjyaiuevIIAUjf2", // Uch Mengly2
    participantsWillAttend: [
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620", // UI/UX Design
    participantCount: 3,
  ),
  Event(
    title: "Digital Advertising Strategy",
    description: "Learn strategies for effective online advertising.",
    date: DateTime(2025, 1, 30),
    startTime: "10:30 AM",
    endTime: "3:30 PM",
    location: "San Diego, CA",
    imageUrl: "15",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
    participantsWillAttend: [
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "AqsauIfPHxajYR20eiqGHxyDWxl1"
    ],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "e0359913-2024-447a-bfd2-edff6a9a0728", // Digital Marketing
    participantCount: 3,
  ),
  // Add 18 more events following the same structure
  Event(
    title: "Cyber Resilience Workshop",
    description: "Build strategies to enhance cyber resilience.",
    date: DateTime(2025, 2, 5),
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    location: "Atlanta, GA",
    imageUrl: "16",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
    participantsWillAttend: [
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2"
    ],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886", // Cyber Security
    participantCount: 3,
  ),
  Event(
    title: "Web Accessibility Workshop",
    description: "Ensure your web applications are accessible to all.",
    date: DateTime(2025, 2, 10),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Philadelphia, PA",
    imageUrl: "17",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Uch Mengly4
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "m18RsrYElTR0tTjyaiuevIIAUjf2"
    ],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb", // Web/App Development
    participantCount: 3,
  ),
  Event(
    title: "AI Ethics Summit",
    description: "Explore the ethical challenges of AI systems.",
    date: DateTime(2025, 2, 15),
    startTime: "11:30 AM",
    endTime: "4:00 PM",
    location: "Portland, OR",
    imageUrl: "18",
    organizerId: "iP8HPYBpQnWIfS3m98jZLZ3MNmW2", // Uch Mengly
    participantsWillAttend: [
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["CqPG0YgwBzaUgDQaTIE6DdToXHZ2"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e", // Artificial Intelligence
    participantCount: 3,
  ),
  Event(
    title: "Data Analytics Bootcamp",
    description: "Learn how to analyze and visualize data.",
    date: DateTime(2025, 2, 20),
    startTime: "9:00 AM",
    endTime: "6:00 PM",
    location: "San Antonio, TX",
    imageUrl: "19",
    organizerId: "m18RsrYElTR0tTjyaiuevIIAUjf2", // Uch Mengly2
    participantsWillAttend: [
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: true,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f", // Data Science
    participantCount: 3,
  ),
  Event(
    title: "UI/UX Design Tools",
    description: "A hands-on workshop for learning design tools.",
    date: DateTime(2025, 2, 25),
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    location: "San Jose, CA",
    imageUrl: "20",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "CqPG0YgwBzaUgDQaTIE6DdToXHZ2"
    ],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620", // UI/UX Design
    participantCount: 3,
  ),
  Event(
    title: "Digital Content Creation Masterclass",
    description: "Create compelling content for digital platforms.",
    date: DateTime(2025, 3, 1),
    startTime: "9:30 AM",
    endTime: "4:30 PM",
    location: "Nashville, TN",
    imageUrl: "21",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
    participantsWillAttend: [
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2"
    ],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: true,
    categoryId: "e0359913-2024-447a-bfd2-edff6a9a0728", // Digital Marketing
    participantCount: 3,
  ),
  // Add 13 more events following this structure
  Event(
    title: "Blockchain Innovations Meetup",
    description: "Learn about blockchain's potential in the modern world.",
    date: DateTime(2025, 3, 5),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Austin, TX",
    imageUrl: "22",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3", // Uch Mengly4
    participantsWillAttend: [
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2",
      "AqsauIfPHxajYR20eiqGHxyDWxl1"
    ],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc", // Fintech
    participantCount: 3,
  ),
  Event(
    title: "AI Product Design Hackathon",
    description: "Collaborate to create AI-driven solutions.",
    date: DateTime(2025, 3, 10),
    startTime: "9:00 AM",
    endTime: "6:00 PM",
    location: "Seattle, WA",
    imageUrl: "23",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1", // Uch Mengly6
    participantsWillAttend: [
      "VCYZdLohGbU2vqtd5yRPZTTPXln1",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3"
    ],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e", // Artificial Intelligence
    participantCount: 3,
  ),
  Event(
    title: "Data Privacy Regulation Seminar",
    description: "Stay updated on the latest data privacy laws.",
    date: DateTime(2025, 3, 15),
    startTime: "10:30 AM",
    endTime: "2:00 PM",
    location: "Phoenix, AZ",
    imageUrl: "24",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1", // Uch Mengly5
    participantsWillAttend: [
      "AqsauIfPHxajYR20eiqGHxyDWxl1",
      "qmqllcFjVPgHc0MV4Q4PfehF3hL2",
      "dYDsm4Vogjc4LWLGMaSZCIufQux1"
    ],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886", // Cyber Security
    participantCount: 3,
  ),
  Event(
    title: "UX Patterns for Mobile Apps",
    description: "Design intuitive user interfaces for mobile applications.",
    date: DateTime(2025, 3, 20),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Denver, CO",
    imageUrl: "25",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2", // Uch Mengly3
    participantsWillAttend: [
      "m18RsrYElTR0tTjyaiuevIIAUjf2",
      "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
      "VCYZdLohGbU2vqtd5yRPZTTPXln1"
    ],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620", // UI/UX Design
    participantCount: 3,
  ),
  // Add 6 more hardcoded examples here
  Event(
    title: "Digital Marketing Workshop",
    description: "Discover the latest strategies in digital marketing.",
    date: DateTime(2025, 4, 1),
    startTime: "9:00 AM",
    endTime: "3:00 PM",
    location: "New York, NY",
    imageUrl: "26",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["AqsauIfPHxajYR20eiqGHxyDWxl1", "dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "e0359913-2024-447a-bfd2-edff6a9a0728",
    participantCount: 2,
  ),
  Event(
    title: "Cloud Computing Trends Seminar",
    description: "Explore the emerging trends in cloud technology.",
    date: DateTime(2025, 4, 5),
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    location: "San Francisco, CA",
    imageUrl: "27",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["VCYZdLohGbU2vqtd5yRPZTTPXln1", "m18RsrYElTR0tTjyaiuevIIAUjf2"],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: false,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620",
    participantCount: 2,
  ),
  Event(
    title: "Startup Growth Strategies",
    description: "Learn actionable strategies for growing your startup.",
    date: DateTime(2025, 4, 10),
    startTime: "9:30 AM",
    endTime: "5:00 PM",
    location: "Austin, TX",
    imageUrl: "28",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "Blockchain Beyond Cryptocurrency",
    description: "A deep dive into blockchain applications beyond finance.",
    date: DateTime(2025, 4, 15),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Boston, MA",
    imageUrl: "29",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc",
    participantCount: 2,
  ),
  Event(
    title: "Future of Artificial Intelligence",
    description: "Discuss the implications of AI in society.",
    date: DateTime(2025, 4, 20),
    startTime: "11:00 AM",
    endTime: "5:00 PM",
    location: "Seattle, WA",
    imageUrl: "30",
    organizerId: "dYDsm4Vogjc4LWLGMaSZCIufQux1",
    participantsWillAttend: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
  Event(
    title: "Cybersecurity for Small Businesses",
    description: "Practical tips for securing your small business.",
    date: DateTime(2025, 4, 25),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "Los Angeles, CA",
    imageUrl: "31",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886",
    participantCount: 2,
  ),
  Event(
    title: "Data Science Bootcamp",
    description: "Intensive hands-on workshop in data science.",
    date: DateTime(2025, 5, 1),
    startTime: "8:00 AM",
    endTime: "4:00 PM",
    location: "Chicago, IL",
    imageUrl: "32",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: false,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f",
    participantCount: 2,
  ),
  Event(
    title: "UI/UX Design Principles",
    description: "Master key principles of effective design.",
    date: DateTime(2025, 5, 5),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Miami, FL",
    imageUrl: "33",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["VCYZdLohGbU2vqtd5yRPZTTPXln1", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620",
    participantCount: 2,
  ),
  // Continue adding more hardcoded events until 20 total
  Event(
    title: "E-commerce Optimization Strategies",
    description: "Enhance your e-commerce platform with proven strategies.",
    date: DateTime(2025, 5, 10),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "San Diego, CA",
    imageUrl: "34",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "Ethical Hacking 101",
    description: "Learn ethical hacking basics and tools.",
    date: DateTime(2025, 5, 15),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "Austin, TX",
    imageUrl: "35",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886",
    participantCount: 2,
  ),
  Event(
    title: "Data Visualization Masterclass",
    description: "Create impactful data visualizations using top tools.",
    date: DateTime(2025, 5, 20),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Boston, MA",
    imageUrl: "36",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["AqsauIfPHxajYR20eiqGHxyDWxl1", "VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    participantsJoined: ["AqsauIfPHxajYR20eiqGHxyDWxl1"],
    isPublic: true,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f",
    participantCount: 2,
  ),
  Event(
    title: "Introduction to No-Code Development",
    description: "Build apps without coding experience.",
    date: DateTime(2025, 5, 25),
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    location: "San Francisco, CA",
    imageUrl: "37",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "AI in Healthcare",
    description: "Exploring how AI is transforming the healthcare industry.",
    date: DateTime(2025, 5, 30),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "New York, NY",
    imageUrl: "38",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: false,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
  Event(
    title: "Advanced Python Programming",
    description: "Master advanced Python features and applications.",
    date: DateTime(2025, 6, 5),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Chicago, IL",
    imageUrl: "39",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["VCYZdLohGbU2vqtd5yRPZTTPXln1", "m18RsrYElTR0tTjyaiuevIIAUjf2"],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f",
    participantCount: 2,
  ),
  Event(
    title: "Digital Art Creation",
    description: "Workshop on creating stunning digital artwork.",
    date: DateTime(2025, 6, 10),
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    location: "Seattle, WA",
    imageUrl: "40",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620",
    participantCount: 2,
  ),
  Event(
    title: "Effective Team Management",
    description: "Techniques for leading and managing teams effectively.",
    date: DateTime(2025, 6, 15),
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    location: "Miami, FL",
    imageUrl: "41",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2", "JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: false,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc",
    participantCount: 2,
  ),
  Event(
    title: "Sustainable Tech Solutions",
    description: "Exploring technologies for a sustainable future.",
    date: DateTime(2025, 6, 20),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Austin, TX",
    imageUrl: "42",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "AqsauIfPHxajYR20eiqGHxyDWxl1"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
  Event(
    title: "Game Development Bootcamp",
    description: "Build your own video games in this intensive bootcamp.",
    date: DateTime(2025, 6, 25),
    startTime: "8:00 AM",
    endTime: "6:00 PM",
    location: "San Diego, CA",
    imageUrl: "43",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "Blockchain for Beginners",
    description: "An introduction to blockchain technology and its uses.",
    date: DateTime(2025, 7, 1),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "San Francisco, CA",
    imageUrl: "44",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "0a45f0e6-61bb-40f9-9ce6-c5f7c1f941dc",
    participantCount: 2,
  ),
  Event(
    title: "Cloud Computing Essentials",
    description: "Understanding the fundamentals of cloud services.",
    date: DateTime(2025, 7, 5),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "Austin, TX",
    imageUrl: "45",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["VCYZdLohGbU2vqtd5yRPZTTPXln1", "dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    participantsJoined: ["VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    isPublic: true,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
  Event(
    title: "Cybersecurity and Risk Management",
    description: "Learn how to mitigate cyber threats and manage risks.",
    date: DateTime(2025, 7, 10),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Los Angeles, CA",
    imageUrl: "46",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2", "iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: false,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886",
    participantCount: 2,
  ),
  Event(
    title: "Digital Marketing Bootcamp",
    description: "Master the art of digital marketing.",
    date: DateTime(2025, 7, 15),
    startTime: "9:00 AM",
    endTime: "2:00 PM",
    location: "New York, NY",
    imageUrl: "47",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "AqsauIfPHxajYR20eiqGHxyDWxl1"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: true,
    categoryId: "e0359913-2024-447a-bfd2-edff6a9a0728",
    participantCount: 2,
  ),
  Event(
    title: "Mobile App Development for iOS",
    description: "Build your first iOS mobile application.",
    date: DateTime(2025, 7, 20),
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    location: "Chicago, IL",
    imageUrl: "48",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3", "dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "Design Thinking Workshop",
    description: "Learn the fundamentals of design thinking.",
    date: DateTime(2025, 8, 1),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "San Francisco, CA",
    imageUrl: "50",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620",
    participantCount: 2,
  ),
  Event(
    title: "JavaScript Frameworks Deep Dive",
    description: "Explore popular JavaScript frameworks in detail.",
    date: DateTime(2025, 8, 5),
    startTime: "1:00 PM",
    endTime: "5:00 PM",
    location: "Los Angeles, CA",
    imageUrl: "51",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "CqPG0YgwBzaUgDQaTIE6DdToXHZ2"],
    participantsJoined: ["m18RsrYElTR0tTjyaiuevIIAUjf2"],
    isPublic: false,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "AI for Business Leaders",
    description: "A guide to AI applications for business decision-making.",
    date: DateTime(2025, 8, 10),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Chicago, IL",
    imageUrl: "52",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
  Event(
    title: "Cybersecurity Incident Response",
    description: "Learn how to respond to a cybersecurity breach.",
    date: DateTime(2025, 8, 15),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "New York, NY",
    imageUrl: "53",
    organizerId: "CqPG0YgwBzaUgDQaTIE6DdToXHZ2",
    participantsWillAttend: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: true,
    categoryId: "268614b1-fd0b-4b33-a24d-6162d4df0886",
    participantCount: 2,
  ),
  Event(
    title: "Advanced Data Science with Python",
    description: "Master advanced data science techniques using Python.",
    date: DateTime(2025, 8, 20),
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Seattle, WA",
    imageUrl: "54",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: false,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f",
    participantCount: 2,
  ),
  Event(
    title: "Augmented Reality Development",
    description: "An introduction to developing AR experiences.",
    date: DateTime(2025, 8, 25),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Austin, TX",
    imageUrl: "55",
    organizerId: "VCYZdLohGbU2vqtd5yRPZTTPXln1",
    participantsWillAttend: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: true,
    categoryId: "735dc0af-501f-46b7-b975-49a304dc0620",
    participantCount: 2,
  ),
  Event(
    title: "Building Scalable Web Apps",
    description: "Learn to build scalable and efficient web applications.",
    date: DateTime(2025, 9, 1),
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    location: "San Francisco, CA",
    imageUrl: "56",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["dYDsm4Vogjc4LWLGMaSZCIufQux1", "VCYZdLohGbU2vqtd5yRPZTTPXln1"],
    participantsJoined: ["dYDsm4Vogjc4LWLGMaSZCIufQux1"],
    isPublic: true,
    categoryId: "1b388593-9fc0-4e12-98e9-85a21f4e07eb",
    participantCount: 2,
  ),
  Event(
    title: "The Future of Data Science",
    description: "What’s next in data science and machine learning?",
    date: DateTime(2025, 9, 5),
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    location: "Chicago, IL",
    imageUrl: "57",
    organizerId: "JSv2GoLB3AX2bu7PHtkTe22o7LF3",
    participantsWillAttend: ["m18RsrYElTR0tTjyaiuevIIAUjf2", "qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    participantsJoined: ["qmqllcFjVPgHc0MV4Q4PfehF3hL2"],
    isPublic: false,
    categoryId: "46219624-d55f-48a4-81a6-c1a22ad0bf4f",
    participantCount: 2,
  ),
  Event(
    title: "Building AI Models from Scratch",
    description: "Step-by-step guide to building AI models from the ground up.",
    date: DateTime(2025, 9, 10),
    startTime: "10:00 AM",
    endTime: "5:00 PM",
    location: "Austin, TX",
    imageUrl: "58",
    organizerId: "AqsauIfPHxajYR20eiqGHxyDWxl1",
    participantsWillAttend: ["iP8HPYBpQnWIfS3m98jZLZ3MNmW2", "JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    participantsJoined: ["JSv2GoLB3AX2bu7PHtkTe22o7LF3"],
    isPublic: true,
    categoryId: "1b34ea8a-bf52-43d3-acaf-38d3ad89bf6e",
    participantCount: 2,
  ),
];
